### PR TITLE
Dots format 🟢🟡🔴

### PR DESCRIPTION
**Pull request by T1xx1**
New dots format with 🟢🟡🔴 discussed in #11 • [here](https://github.com/kisvegabor/abbreviations-in-code/issues/11#issuecomment-1290597794).
Now that the format is changed genJson.pl file doesn't work anymore, I don't know Perl so I'm not able to fix it. If necessary I will open a new issue for that.

I was also thinking about that with GitHub pages it's possible to open an endpoint here on GitHub and with a JS script, the abbr.json file will be retrievable by a URL like an API.

After all, I also recommend adding a CHANGELOG.md to track progress and add a license.

### CODE REVIEW

**Comment by philipeachille** [comment]
Wow, I think that looks cool. Now, arguably, the "-" in front of an abbreviation is not even needed any more, because the coloured dots seemingly serve as bullet points

**Comment by T1xx1** [comment]
Thank you.
I agree with u but there's a problem.
However dashes are used to display the markdown format as I can understand of Perl they are used in the genJson.pl file to separate the line with the "-" char.

**Comment by kisvegabor** [comment]
Wow, it really looks great! I agree that we need to keep the dashes for markdown. 

Do you agree with MIT license?

Similarly to JSON we could generate an `index.html` file too and GitHub pages could display it. The best would be to run `[genJson.pl](https://github.com/kisvegabor/abbreviations-in-code/blob/master/genJson.pl)` in CI.

**Comment by T1xx1** [comment]
Thanks,
Yes the MIT license would be great.
And the site is a great idea. Having the JSON file with JS is easy to generate an HTML without using the genJson.pl

**Comment by T1xx1** [comment]
> Thanks,
> Yes the MIT license would be great.
> And the site is a great idea. Having the JSON file with JS is easy to generate an HTML without using the genJson.pl

Or directly from the md use a website that compile in HTML.

**Comment by kisvegabor** [comment]
> Yes the MIT license would be great.

[Added](https://github.com/kisvegabor/abbreviations-in-code/blob/master/LICENCE).

> And the site is a great idea. Having the JSON file with JS is easy to generate an HTML without using the genJson.pl

Once `genJson.pl` is generating the JSON file it could easily add `<li>` elements to a HTML files too.

> Or directly from the md use a website that compile in HTML.

Using `genJson.pl` seems simpler to me. One script -> less maintenance

**Comment by T1xx1** [comment]
👍

**Comment by kisvegabor** [comment]
Cool, merging. Thank you!

**Pull request merged**
